# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c9tLk-2T6sM84dI4Lwy9nFlET2LX_Fl9
"""

import asyncio
from aiogram import Bot, Dispatcher, F
from aiogram.filters import CommandStart, StateFilter
from aiogram.types import BotCommand

from config import BOT_TOKEN, engine
from models import Base
from states import Registration
from handlers import (
    cmd_start,
    process_phone_contact,
    process_phone_manually,
    process_first_name,
    process_last_name,
    process_gender,
    process_birth_date,
    echo,
)

async def on_startup():
    # Создаём таблицы в БД, если их нет
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    # Устанавливаем команды бота в меню
    bot = Bot.get_current()
    await bot.set_my_commands([
        BotCommand(command="start", description="Начать/перезапустить")
    ])

async def main():
    bot = Bot(token=BOT_TOKEN)
    dp = Dispatcher()
    dp["bot"] = bot

    # Регистрация обработчиков
    dp.message.register(cmd_start, CommandStart())
    dp.message.register(process_phone_contact, Registration.waiting_for_phone, F.contact)
    dp.message.register(process_phone_manually, Registration.waiting_for_phone)
    dp.message.register(process_first_name, Registration.waiting_for_first_name)
    dp.message.register(process_last_name, Registration.waiting_for_last_name)
    dp.callback_query.register(process_gender, Registration.waiting_for_gender, F.data.startswith('gender_'))
    dp.message.register(process_birth_date, Registration.waiting_for_birth_date)
    dp.message.register(echo, StateFilter(None))

    await on_startup()

    try:
        await dp.start_polling(bot)
    finally:
        await bot.session.close()

if __name__ == '__main__':
    asyncio.run(main())